- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Updating apt package index
      command: apt-get update

    - name: Install Docker
      command: apt-get install -y docker.io

    - name: Start Docker service
      command: systemctl start docker

    - name: Deploy your Docker container
      command: docker run -itd --name my-container -p 8084:8081 bindukantharaju/staragileprojectbanking:v1

